# To build and run:
# docker build -f Dockerfile.dev -t catalogo .
# docker run catalogo

# build stage
FROM gradle:7.6.1-jdk17 AS builder

WORKDIR /usr/app/

COPY . .

RUN gradle bootJar

# build runtime
FROM eclipse-temurin:17.0.5_8-jre

COPY build/libs/*.jar /opt/app/application.jar

RUN addgroup --system spring && adduser --system spring --ingroup spring
USER spring:spring

CMD java -jar /opt/app/application.jar
